# running 4 front end servers
version: "3"
services:
  instance0:
    image: whisper.io
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  instance1:
    image: whisper.io
    ports:
      - "3001:3000"
    volumes:
      - .:/app
  instance2:
    image: whisper.io
    ports:
      - "3002:3000"
    volumes:
      - .:/app
  instance3:
    image: whisper.io
    ports:
      - "3003:3000"
    volumes:
      - .:/app
  
