name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 20

      # - name: Install dependencies
      #   run: npm install

      # - name: Build the app
      #   run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_TAG }}

  deploy-to-vm:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Pulling Docker Image and Restart Container via SSH Agent
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_ADDRESS }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd app && ./update-all.sh